on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: Discontract/github-action-slack-notify-deployment@v1
with:
  channel: deployments
  status: STARTED
  color: good
env:
         SLACK_BOT_TOKEN: ${{ secrets.MY_SECRET }}
          SLACK_MESSAGE: 'https://kidologinrjs.web.app/'
          SLACK_TITLE: 'Slack Notification Demo'